### PR TITLE
Set a valid object_type for the registration request

### LINKED ISSUE #72: [sdr-api/stage] Dor::Services::Client::UnexpectedResponse: Bad Request: 400 (Unknown item type: 'object')
## Backtrace

    line 9 of [PROJECT_ROOT]/app/controllers/resources_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/67994/faults/59446521)

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
The previous value was not a valid option.
Fixes #72

## Was the documentation (README.md, openapi.yml) updated?

n/a

### CODE REVIEW

File: app/controllers/resources_controller.rb [hunk 1]
```diff
@@ -33,6 +33,8 @@ def register_params
     reg_params[:metadata_source] = col_catkey ? 'label' : 'symphony'
     reg_params[:other_id] = "symphony:#{col_catkey}" if col_catkey
     reg_params[:collection] = params[:structural][:isMemberOf]
+    # TODO: content_type (tag Process:Content Type:Book (ltr) ) can come from a lookup using params[:type]
+    # reg_param[:tags] = ['Process:Content Type:Book (ltr)']
```
Comment (ndushay) [inline app/controllers/resources_controller.rb]: is this already ticketed?

Comment (jcoyne) [reply app/controllers/resources_controller.rb]: I'll do that now.
